package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test")) {
    params {
        expect {
            param("system.ALL_TESTS_NUM", "10000")
        }
        update {
            param("system.ALL_TESTS_NUM", "50")
        }
        expect {
            param("system.TEST_LOG_LINES_NUM", "100")
        }
        update {
            param("system.TEST_LOG_LINES_NUM", "10")
        }
    }

    expectSteps {
        script {
            scriptContent = "./generate_fake_run.sh %system.ALL_TESTS_NUM% %system.FAILED_TESTS_PERCENTAGE% %system.TEST_LOG_LINES_NUM%"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                ./generate_fake_run.sh %system.ALL_TESTS_NUM% %system.FAILED_TESTS_PERCENTAGE% %system.TEST_LOG_LINES_NUM%
                cat a.txt
            """.trimIndent()
        }
    }
}
