package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test")) {
    params {
        expect {
            param("system.ALL_TESTS_NUM", "10000")
        }
        update {
            param("system.ALL_TESTS_NUM", "50")
        }
        expect {
            param("system.TEST_LOG_LINES_NUM", "100")
        }
        update {
            param("system.TEST_LOG_LINES_NUM", "10")
        }
    }
}
