package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'WithRetry'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("WithRetry")
    name = "WithRetry"

    params {
        param("system.ALL_TESTS_NUM", "50")
        param("system.TEST_LOG_LINES_NUM", "10")
        param("system.FAILED_TESTS_PERCENTAGE", "30")
    }

    vcs {
        root(RelativeId("TCTestDataRepo"), "generated-tests =>")
    }

    steps {
        script {
            scriptContent = "./generate_fake_run.sh %system.ALL_TESTS_NUM% %system.FAILED_TESTS_PERCENTAGE% %system.TEST_LOG_LINES_NUM%"
        }
    }
}))

